package com.evermc.horde.utils;

import com.evermc.horde.Horde;
import com.velocitypowered.api.proxy.Player;
import com.velocitypowered.api.proxy.server.RegisteredServer;
import net.kyori.adventure.identity.Identity;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.minimessage.MiniMessage;
import net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializer;
import net.kyori.adventure.text.serializer.plain.PlainTextComponentSerializer;

import java.util.Arrays;
import java.util.UUID;

@SuppressWarnings("unused") //Some utils are pre-installed for future use
public class MessagingUtils {

    /**
     * Sends a message to all players on the proxy.
     *
     * @param message the message to send
     */
    public static void sendMessageToAll(Component message) {
        Horde.server.getAllPlayers().forEach(player -> player.sendMessage(message));
    }

    /**
     * Sends a message to all players, attributing it to the given author's UUID using Adventure Identity.
     *
     * @param authorUuid the UUID of the message author
     * @param message the message to send
     */
    @SuppressWarnings("deprecation") // Sending unsigned UUID is not supported by secure profiles
    public static void sendMessageToAllAs(UUID authorUuid, Component message) {
        final var identity = Identity.identity(authorUuid);
        Horde.server.getAllPlayers().forEach(player -> player.sendMessage(identity, message));
    }

    /**
     * Sends a message to all players on a given Velocity server.
     *
     * @param server the name of the server to send the message to
     * @param message the message to send
     */
    public static void sendMessageToServer(RegisteredServer server, Component message) {
        server.getPlayersConnected().forEach(player -> player.sendMessage(message));
    }

    /**
     * Sends a message to all players on a given Velocity server, attributing it to the given author's UUID using Adventure Identity.
     *
     * @param authorUuid the UUID of the message author
     * @param server the name of the server to send the message to
     * @param message the message to send
     */
    @SuppressWarnings("deprecation") // Sending unsigned UUID is not supported by secure profiles
    public static void sendMessageToServerAs(UUID authorUuid, RegisteredServer server, Component message) {
        final var identity = Identity.identity(authorUuid);
       server.getPlayersConnected().forEach(player -> player.sendMessage(identity, message));
    }

    /**
     * Deserializes a string into a {@link Component} using the currently configured
     * chat message format.
     *
     * @param message the string to deserialize
     * @return the deserialized component
     */
    public static Component deserializeChatMessage(String message) {
        if(Horde.config.getConfig().node("enable-legacy-chat-formatting").getBoolean()) {
            // Replace & with § for legacy formatting
            return LegacyComponentSerializer.legacySection().deserialize(message.replace('&', '§'));
        } else {
            return MiniMessage.miniMessage().deserialize(message);
        }
    }

    /**
     * Looks up a value in the given map and returns it.
     *
     * @param path the path to the map in the localization config
     * @param key the key to look up in the map
     * @return the value associated with the key if it exists, or an empty string if it does not
     */
    public static String processNameMappings(String path, String key) {
        return Horde.localization.getMap(path).get(key).getString();
    }

    /**
     * Prepares an array of placeholders for use in chat messages.
     * <p>
     * The returned array is of the form {placeholder1, value1, placeholder2, value2, ...}
     * where the placeholders are the fixed basic placeholders "server" and "player",
     * followed by the permission prefix placeholders as generated by
     * {@link PrefixConfig#processPermissionPrefix(Player)}.
     *
     * @param player the player to generate placeholders for
     * @return the array of placeholders
     */
    @SuppressWarnings("OptionalGetWithoutIsPresent")
    public static String[] prepareChatPlaceholders(Player player) {
        String[] metadata = new String[]{
                "server", MessagingUtils.processNameMappings("SERVER_NAME_MAPPINGS",
                player.getCurrentServer().get().getServerInfo().getName()),
                "player", player.getUsername()
        }; // Fixed basic placeholders
        String[] prefix = Horde.prefixes.processPermissionPrefix(player); // Permission prefix
        String[] placeholders = Arrays.copyOf(metadata, metadata.length + prefix.length);
        System.arraycopy(prefix, 0, placeholders, metadata.length, prefix.length);
        return placeholders;
    }

    /**
     * Logs a message to the logger using the INFO level.
     *
     * @param message the message to log
     */
    public static void logMessage(Component message) {
        Horde.logger.info(PlainTextComponentSerializer.plainText().serialize(message));
    }

    /**
     * Broadcasts a message to all players on all servers, either as an unsigned message
     * or with the UUID of the sender attached, depending on the configuration.
     * <p>
     * If the configuration node "forward-sender-uuid" is true, the message is sent
     * using {@link #sendMessageToAllAs(UUID, Component)} and the UUID of the sender
     * is attached. Otherwise, the message is sent using {@link #sendMessageToAll(Component)}.
     * <p>
     * If the configuration node "log-messages" is true, the message is also logged to the
     * logger using the INFO level.
     *
     * @param uuid the UUID of the sender
     * @param message the message to broadcast
     */
    public static void broadcastAsConfigured(UUID uuid, Component message) {
        if(Horde.config.getConfig().node("forward-sender-uuid").getBoolean()) {
            sendMessageToAllAs(uuid, message);
        } else {
            sendMessageToAll(message);
        }
        if(Horde.config.getConfig().node("log-messages").getBoolean()) {
            logMessage(message);
        }
    }

    /**
     * Sends a message to all players on a given Velocity server, either as an unsigned message
     * or with the UUID of the sender attached, depending on the configuration.
     * <p>
     * If the configuration node "forward-sender-uuid" is true, the message is sent
     * using {@link #sendMessageToServerAs(UUID, RegisteredServer, Component)} and the UUID of the sender
     * is attached. Otherwise, the message is sent using {@link #sendMessageToServer(RegisteredServer, Component)}.
     * <p>
     * If the configuration node "log-messages" is true, the message is also logged to the
     * logger using the INFO level.
     *
     * @param uuid the UUID of the sender
     * @param server the name of the server to send the message to
     * @param message the message to send
     */
    public static void sendLocallyAsConfigured(UUID uuid, RegisteredServer server, Component message) {
        if(Horde.config.getConfig().node("forward-sender-uuid").getBoolean()) {
            sendMessageToServerAs(uuid, server, message);
        } else {
            sendMessageToServer(server, message);
        }
        if(Horde.config.getConfig().node("log-messages").getBoolean()) {
            logMessage(message);
        }
    }

}
